### ISSUE TITLE
brain_fusion package is broken.

### ISSUE THREAD

**Issue by jtaxiexpress** [KarlMathuthu/stability_image_generation#1]
Do you know?
It is already archived.

We want to work together to find a solution.

**Comment by KarlMathuthu** [comment]
Hi bro, Yes i just noticed that. If you want us to work together find the solution, Please close this issue and contact me with either of these.

Email : karlmathuthu11@gmail.com
Whatsapp : +27 65 723 5193

Thanks bro.
