### ISSUE TITLE
Free and unlimited DALLE and Stable Diffusion API 

### ISSUE THREAD

**Issue by Metim0l** [KarlMathuthu/stability_image_generation#2]
Good day! I recommend trying my completely free and unlimited image generator api. 70 different models are available. I hosted them myself on my servers. I guarantee stability.

https://github.com/metim0l/VisionCraft

**Comment by KarlMathuthu** [comment]
After you contact me, You may as well as close this issue. 

More contact information.

karlmathuthu11@gmail.com
karlmathuthu07@gmail.com
karl@stratida.com
